### ISSUE TITLE
Unable to checkout some files to filesystem on Windows

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/kumascript#61]
They use a colon, Microsoft Windows does not support such a file name.

```
>git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    macros/DekiScript:Date.ejs
        deleted:    macros/DekiScript:Page.ejs
        deleted:    macros/DekiScript:String.ejs
        deleted:    macros/DekiScript:Uri.ejs
        deleted:    macros/DekiScript:Web.ejs
        deleted:    macros/DekiScript:Wiki.ejs
        deleted:    macros/HTML:Element_Navigation.ejs
        deleted:    macros/InterfaceStatus:EXPERIMENTAL.ejs
        deleted:    macros/InterfaceStatus:FROZEN.ejs
        deleted:    macros/InterfaceStatus:FROZEN:DisplayName.ejs
        deleted:    macros/InterfaceStatus:Scriptable_no.ejs
        deleted:    macros/InterfaceStatus:Scriptable_yes.ejs
        deleted:    macros/InterfaceStatus:UNDER_REVIEW.ejs
        deleted:    macros/InterfaceStatus:unfrozen.ejs
        deleted:    macros/InterfaceStatus:unfrozen:DisplayName.ejs
        deleted:    macros/L10n:CSS.css
        deleted:    macros/L10n:Common.json
        deleted:    macros/L10n:CompatTable.json
        deleted:    macros/L10n:HTML.json
        deleted:    macros/L10n:JavaScript.json
        deleted:    macros/L10n:SVG.json
        deleted:    macros/MDN:Common.ejs
        deleted:    macros/RSS:Element_Navigation.ejs
        deleted:    macros/Storage:synchronous_io_warning.ejs
        deleted:    macros/Storage:threadsafety_callback_warning.ejs
        deleted:    macros/Storage:type_conversion_warning.ejs
        deleted:    macros/XUL:xul_element.ejs
        deleted:    macros/xul:box.ejs
        deleted:    macros/xul:hbox.ejs
        deleted:    macros/xul:vbox.ejs

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        macros/L10n
        macros/MDN
        macros/RSS
        macros/Storage
        macros/XUL

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by jwhitlock** [comment]
The colon (``:``) is one of the characters that can't be used in a filename on a Windows filesystem, and we should change the filenames of these macros that use it.  The set of disallowed characters ([MSDN source](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx)) are:

* ``<`` (less than)
* ``>`` (greater than)
* ``:`` (colon)
* ``"`` (double quote)
* ``/`` (forward slash)
* ``\`` (backslash)
* ``|`` (vertical bar or pipe)
* ``?`` (question mark)
* ``*`` (asterisk)

We're already normalizing case, so that ``{{CompatNo}}`` and ``{{compatno}}`` both work. Maybe we can extend this so that the filename for ``{{MDN:Common}}`` is **one** of:

* ``MDN_Common.ejs``
* ``MDN-Common.ejs``
* ``MDN.Common.ejs``

The macro usage could still include the colon.

Or, we could change all the internal usage of these macros in one PR. I'll need to double check if any "colon-macros" are used on pages.

**Comment by jwhitlock** [comment]
I have found some examples of "colon-macros" used on MDN pages. For example, this page:

https://developer.mozilla.org/en-US/Add-ons/Code_snippets/File_I_O

uses ``{{ Storage:synchronous_io_warning() }}`` several times. So, we will need to translate colons in KumaScript macro names into file-safe characters.

My preference is ``Storage-synchronous_io_warning.ejs``.  It looks a little clumsy, but moves toward dashes for namespacing rather than colons.

**Comment by jwhitlock** [comment]
The staff discussed this and agreed to use a dash (``-``) instead of a colon (``:``) in the filenames.  The tasks are:

* [ ] Normalize colons to dashes, maybe in [getTemplateName](https://github.com/mozilla/kumascript/blob/master/lib/kumascript/loaders.js#L129).
* [ ] Rename the macros.
